### PR TITLE
[SB] Setup Nativewind

### PR DESCRIPTION
**Pull request by sethonne**
- Installed dependencies for nativewind
- Initialized tailwind config and added it to babel config

### CODE REVIEW

**Comment by 0-BSCode** [comment]
Any way we can get rid of this error popping up?
image

**Comment by 0-BSCode** [comment]
Could you link to the docs you used for setup?

**Comment by sethonne** [comment]
Here it is https://www.nativewind.dev/quick-starts/expo

**Comment by sethonne** [comment]
> Any way we can get rid of this error popping up? image

[Stackoverflow solution](https://stackoverflow.com/questions/72909992/react-native-typescript-giving-me-an-ts-error-when-using-classname)

Apparently it's a ts thing. Got rid of it by including nativewind types in my recent commit.

**Review by 0-BSCode — APPROVED** [review]
LGTM

**Pull request merged**
